### ISSUE TITLE
Patch for race condition

### ISSUE THREAD

**Issue by vincentjames501** [GlennChiu/GCNetworkReachability#5]
I'm not an expert in this at all which is why I'm not submitting this as a pull request but rather as a review.  I keep getting exceptions on the line below because `stopMonitoringNetworkReachability` was called and then `s_self->_handler_blk` is `NULL` inside the `dispatch_async`.  Clearly this is a race condition.

``` objective-c
if (s_self) dispatch_async(dispatch_get_main_queue(), ^{s_self->_handler_blk(status);});
```

From within this code block:

``` objective-c
void(^cb_blk)(GCNetworkReachabilityStatus) = ^(GCNetworkReachabilityStatus status) {

        GCNetworkReachability *s_self = w_self;
        if (s_self) dispatch_async(dispatch_get_main_queue(), ^{s_self->_handler_blk(status);});
    };
```

I believe we could change it to something like this:

``` objective-c
    void(^cb_blk)(GCNetworkReachabilityStatus) = ^(GCNetworkReachabilityStatus status) {

        GCNetworkReachability *s_self = w_self;
        if (s_self) {
            void(^_blk_cpy)(GCNetworkReachabilityStatus) = s_self->_handler_blk;
            if(_blk_cpy) {
                dispatch_async(dispatch_get_main_queue(), ^{_blk_cpy(status);});
            }
        }
    };
```

so that we hold onto a reference in the `dispatch_async` and make sure the `_blk_cpy` is not `NULL`

Thoughts?

**Comment by GlennChiu** [comment]
Fixed
